### ISSUE TITLE
csv?

### ISSUE THREAD

**Issue by kendonB** [dixoncheng/covid19map#12]
Kia ora - are you able to output the raw data from the MoH page as a csv with a stable link? Thank you so much for putting this together!

**Comment by dixoncheng** [comment]
Yeah I can look into that, what are you planning on doing with it?

**Comment by kendonB** [comment]
No immediate plans but good for local and international researchers to be able to use something easily

**Comment by simeonmiteff** [comment]
@kendonB I have an API that offers CSV, JSON and GeoJSON: https://nzcovid19api.xerra.nz/

Core code is available here (PRs welcome): https://github.com/simeonmiteff/nzcovid19cases

**Comment by simeonmiteff** [comment]
@kendonB FYI, I have also added the alert level: https://nzcovid19api.xerra.nz/alertlevel/json

**Comment by simeonmiteff** [comment]
@kendonB  FYI, I have added MSD COVID-19 hardship grants information: https://nzcovid19api.xerra.nz/grants/json

If this is something useful to you, I could add CSV format too.
