### ISSUE TITLE
Use API at https://nzcovid19api.xerra.nz/?

### ISSUE THREAD

**Issue by simeonmiteff** [dixoncheng/covid19map#14]
Nice work on this site.

I'm not sure if that adds value, but I built this over the weekend and I note you're doing similar stuff (scraping and normalising the data). Code for the core functions is published here: https://github.com/simeonmiteff/nzcovid19cases (PRs welcome).

**Comment by dixoncheng** [comment]
Nice work! I was wondering if someone had built something like this. I'll look into it, thanks!

**Comment by simeonmiteff** [comment]
@dixoncheng FYI, I have also added the alert level: https://nzcovid19api.xerra.nz/alertlevel/json

**Comment by simeonmiteff** [comment]
@dixoncheng FYI, I have added MSD COVID-19 hardship grants information: https://nzcovid19api.xerra.nz/grants/json

**Comment by simeonmiteff** [comment]
@dixoncheng FYI: https://nzcovid19api.xerra.nz/casestats/json

**Comment by dixoncheng** [comment]
Due to the constant changing of the layout of the MoH page, I had to adapt very quickly and the need to keep historical data that's no longer on the page, I had to write my own api. Thanks again for the offer.
